export const pricingCards = [
  {
    id: "1",
    title: "Starter",
    description: "Perfect for trying out jamly",
    price: "Free",
    duration: "",
    highlight: "Key features",
    features: ["10 product list", "2 Team members", "Basic Analytics"],
    priceId: "",
  },
  {
    id: "2",
    title: "Jamly Unlimited",
    description: "The ultimate store kit",
    price: "NGN 20,000",
    duration: "month",
    highlight: "Key features",
    features: [
      "Unlimited Product list",
      "24/7 Support team",
      "10 team members",
      "Advanced Analytics",
    ],
    priceId: "PLN_n9u9ypf43pk6vti",
  },
  {
    id: "3",
    title: "Basic",
    description: "For serious store owners",
    price: "NGN 7000",
    duration: "month",
    highlight: "Everything in Starter, plus",
    features: ["Unlimited Product list", "5 Team members", "Basic Analytics"],
    priceId: "PLN_4elei0drizjfiie",
  },
];
